spring:
   application:
    name: FakeCommerceApplication
   datasource:
    url: jdbc:mysql://localhost:3306/fakecommerce?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password: 'next24@yrM'
    driver-class-name: com.mysql.cj.jdbc.Driver
   flyway:
    enabled: true
    locations: classpath:db/migration
   jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
